name: example

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_i18next:
    path: ../
  cupertino_icons: ^0.1.2
  http:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

environment:
  sdk: '>=1.19.0 <3.0.0'