name: flutter_i18next
description: i18next for Flutter.
version: 0.1.0
homepage: https://github.com/Taskulu/flutter_i18next

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  yaml: ^3.1.0
  xml2json: ^5.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
