name: flutter_i18next
description: i18next for Flutter.
version: 0.1.0
homepage: https://github.com/Taskulu/flutter_i18next

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.16.0
  yaml: ^2.2.0
  xml2json: ^4.2.0
  merge_map: ^1.0.2
  universal_io: ^1.0.1
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

environment:
  sdk: '>=2.3.0 <3.0.0'
