name: flutter_i18next
description: An internationalization package for Flutter using i18next standards.
version: 0.3.0
homepage: https://github.com/Taskulu/flutter_i18next

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
  xml2json: ^5.0.0
  universal_io: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'
